### PR TITLE
Fixes #568 : DS whose virtual system is referencing a SFC, can be del…

### LINKED ISSUE #568: Should be able to delete DS when sfc is not binded to a security group
### Description
In neutron sfc, when sfc is not binded  to security group, any Deployment spec under virtual systems connected to the given sfc , can be deleted

### Expected Behavior
Should be able to delete DS under a virtual system connected a sfc, if any SG is binding to the give sfc.
### Actual Behavior
Deletion of DS fails with an exception saying cannot delete DS referencing to a sfc, even though the sfc is not binded to any SG
### Steps to Reproduce
1. Create SFC chain with atleast one virtual system
2. Configure a DS  under the virtual system
3. now delete the DS.
### Additional Information
This is a requirement change proposed by Arvind , on DS deletion with SFC plugin
### Environment
- OSC Version/Build: 
OSC build -118
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ x] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

### PR DESCRIPTION
**Pull request by karimull**
…eted as long as this SFC is not binded to any of security groups

### CODE REVIEW

File: osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java [hunk 1]
```diff
@@ -113,18 +118,36 @@ private void validateAndLoad(EntityManager em, BaseDeleteRequest request) throws
...
+
+    private void checkSfcAndBinding(EntityManager em,  VirtualSystem vs) throws Exception {
+        if (!vs.getServiceFunctionChains().isEmpty()) {
+            //Look if these SFCs are binded to any of the SG of same tenant as of DS
+            for (ServiceFunctionChain sfc : vs.getServiceFunctionChains()) {
+                List<SecurityGroup> sgList = SecurityGroupEntityMgr.listSecurityGroupsBySfcIdAndProjectId(em,
+                        sfc.getId(), this.ds.getProjectId());
+                if (sgList.stream().anyMatch(sg -> !sg.getMarkedForDeletion())) {
+                    throw new VmidcBrokerValidationException(String.format(
+                            "Cannot delete deployment spec with name '%s' which is currently referencing Service Function Chain %s and binding to a SecurityGroup",
```
Comment (arvindn05) [inline osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java]: Cannot delete deployment spec with name '%s' which is currently referencing Service Function Chain '%s' and binded to the SecurityGroups '%s'

Please update message to above. It would be good to know which SG are referencing this DS

we can comma separate the sg names

File: osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java [hunk 2]
```diff
@@ -113,18 +118,38 @@ private void validateAndLoad(EntityManager em, BaseDeleteRequest request) throws
...
         }
     }
+
+    private void checkSfcAndBinding(EntityManager em, VirtualSystem vs) throws Exception {
+        if (!vs.getServiceFunctionChains().isEmpty()) {
+            //Look if these SFCs are binded to any of the SG of same tenant as of DS
+            for (ServiceFunctionChain sfc : vs.getServiceFunctionChains()) {
+                List<SecurityGroup> sgList = SecurityGroupEntityMgr.listSecurityGroupsBySfcIdAndProjectId(em,
+                        sfc.getId(), this.ds.getProjectId());
+                SecurityGroup sgActive = sgList.stream().filter(sg -> !sg.getMarkedForDeletion()).findFirst()
```
Comment (arvindn05) [inline osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java]: you can give all the sg names comma seperated.

stream()
                .filter(sg -> !sg.getMarkedForDeletion()).map(sg -> sg.getName()).collect(Collectors.joining(", "))

File: osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java [hunk 3]
```diff
@@ -113,18 +118,38 @@ private void validateAndLoad(EntityManager em, BaseDeleteRequest request) throws
...
+                        .orElse(null);
+                if (sgActive != null) {
+                    throw new VmidcBrokerValidationException(String.format(
+                            "Cannot delete deployment spec with name '%s' which is currently referencing Service Function Chain %s and binding to a SecurityGroup %s",
```
Comment (arvindn05) [inline osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java]: also for name/id;'s please make sure they are in ' '. Here for Service function chain ' ' are missing.
binding -> binded to SecurityGroup(s) '%s'

File: osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java [hunk 4]
```diff
@@ -113,18 +118,38 @@ private void validateAndLoad(EntityManager em, BaseDeleteRequest request) throws
...
+
         if (!this.ds.getMarkedForDeletion() && request.isForceDelete()) {
             throw new VmidcBrokerValidationException(
                     "Deployment Spec '"
                             + this.ds.getName()
                             + "' is not marked for deletion and force delete operation is applicable only for entries marked for deletion.");
         }
     }
+
+    private void checkSfcAndBinding(EntityManager em, VirtualSystem vs) throws Exception {
```
Comment (arvindn05) [inline osc-server/src/main/java/org/osc/core/broker/service/DeleteDeploymentSpecService.java]: validateDsNotUsedBySg or something similar to convey the meaning.

**Comment by mrajora-1** [comment]
Verified with Build Version: 1.0.0-SNAPSHOT (Build:142-g0fb43fe, 2017-10-26T07:20:58Z)
Able to delete the DS when SG is not sfc-binded to the DA

[securityBroker-DS-deleted-when-SFC-SG-unbinded.log](https://github.com/opensecuritycontroller/osc-core/files/1420381/securityBroker-DS-deleted-when-SFC-SG-unbinded.log)

**Comment by mrajora-1** [comment]
Verified with Build Version: 1.0.0-SNAPSHOT (Build:142-g0fb43fe, 2017-10-26T07:20:58Z)
Able to delete the DS when SG is not sfc-binded to the DA

securityBroker-DS-deleted-when-SFC-SG-unbinded.log
